vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set colorcolumn=72")
vim.cmd("map <C-S-h> :bprevious<CR>")
vim.cmd("map <C-S-l> :bnext<CR>")
vim.cmd("map <C-h> <C-W>h")
vim.cmd("map <C-j> <C-W>j")
vim.cmd("map <C-k> <C-W>k")
vim.cmd("map <C-l> <C-W>l")
vim.g.mapleader = " "
